apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-monitoring
  namespace: argocd
  annotations:
    # this app depends on prometheus-stack being up first
    # because ServiceMonitor CRD needs to exist
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/harikrishnanaik13-jpg/argocd-gitops
    targetRevision: HEAD
    path: prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  # automated sync with retry — ServiceMonitor CRD may not exist immediately
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
